package cz.cvut.fel.ear.carstatus.statistics;

import cz.cvut.fel.ear.carstatus.builders.StatisticsBuilder;
import cz.cvut.fel.ear.carstatus.enums.ELoggerLevel;
import cz.cvut.fel.ear.carstatus.enums.EStatisticsType;
import cz.cvut.fel.ear.carstatus.filters.*;
import cz.cvut.fel.ear.carstatus.interfaces.IFilter;
import cz.cvut.fel.ear.carstatus.interfaces.IStatistics;
import cz.cvut.fel.ear.carstatus.log.Logger;
import cz.cvut.fel.ear.carstatus.model.Roadpath;
import cz.cvut.fel.ear.carstatus.model.Roadtrip;
import cz.cvut.fel.ear.carstatus.service.RoadTripService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;

@Service
public class StatisticsFactory {

    private final Logger logger = new Logger();
    RoadTripService roadTripService;
    @Autowired
    public StatisticsFactory(RoadTripService service) {
        this.roadTripService = service;
    }

    public Statistics getStatistics(StatisticsFilter filter) {

        if (filter.getFrom() == null && filter.getTo() == null) {
            return getCompleteStatistics(filter);
        }
        if (filter.getTo() != null && filter.getFrom() == null) {
            return getPreStatistics(filter);
        }
        else {
            if (filter.getFrom() == null) {
                filter.setFrom(new Date(Long.MIN_VALUE));
            }
            return getPeriodStatistics(filter);
        }
    }

    private StatisticsBuilder getStatisticsReady(StatisticsFilter filter) {
        IFilter handler = new NoFilter();
        IFilter driver = new DriverFilter();
        IFilter destination = new DestinationFilter();
        IFilter time = new TimeFilter();
        IFilter malfunction = new MalfunctionFilter();
        handler.setNext(driver);
        driver.setNext(destination);
        destination.setNext(time);
        time.setNext(malfunction);
        List<Roadtrip> filtered = handler.handleRequest(filter,roadTripService.findAll());
        return new StatisticsBuilder().numberOfKm(filtered).numberOfRoadtrips(filtered).averageSpeed(filtered).maxSpeed(filtered);
    }

    public Statistics getCompleteStatistics(StatisticsFilter filter) {
        logger.log("Complete statistics were generated by application.", ELoggerLevel.INFO);
        return getStatisticsReady(filter).type(EStatisticsType.COMPLETE).build();
    }
    public Statistics getPreStatistics(StatisticsFilter filter) {
        logger.log("Previous statistics were generated based on provided date.", ELoggerLevel.INFO);
        return getStatisticsReady(filter).type(EStatisticsType.PRE).build();
    }

    public Statistics getPeriodStatistics(StatisticsFilter filter) {
        logger.log("Period statistics were generated based on provided dates.", ELoggerLevel.INFO);
        return getStatisticsReady(filter).type(EStatisticsType.PERIOD).build();
    }
}
